---
- name: Install libs on Debian/Ubuntu
  hosts: localhost
  gather_facts: true

  tasks:

    - name: install
      shell: "sudo apt install qemu-kvm libvirt-daemon libvirt-daemon-system network-manager"
      become: yes
      when: ansible_os_family == 'Debian'

    - name: usermod libvirtd
      shell: "usermod -aG libvirtd $(whoami)"
      become: yes
      when: ansible_os_family == 'Debian'

    - name: newgrp libvirtd
      shell: "newgrp libvirtd"
      become: yes
      when: ansible_os_family == 'Debian'